### ISSUE TITLE
Broker's Choice

### ISSUE THREAD

**Issue by ehildt** [ehildt/config-manager#100]
To enhance the DCCS system, it is desired to implement alternatives to the Redis PubSub. While Redis serves as a cache, it falls short in guaranteeing message delivery. 

* Redis PubSub
Redis PubSub is a lightweight publish-subscribe messaging system provided by Redis. It enables real-time messaging between publishers and subscribers, allowing for decoupled and asynchronous communication. However, Redis PubSub does not guarantee message delivery, which means messages can be lost if subscribers are not actively listening
* Kafka
By implementing Kafka as an alternative, real-time data reception can be ensured, making the DCCS more suitable for scenarios that require timely and reliable data transfer. 
* gRPC
gRPC is a high-performance, language-agnostic communication framework that allows efficient and bidirectional communication between services. It supports various communication patterns, such as unary requests, server streaming, client streaming, and bidirectional streaming. gRPC offers strong typing, automatic code generation, and support for multiple programming languages, making it suitable for building complex distributed systems.

ACC
* implement Kafka and gRPC as an alternative to Redis PubSub
* the user should be able to choose which technology to use, with Redis PubSub to be the default

**Comment by stefanciprian** [comment]
Nest Queues would do the job.
